name: infinidata
favicon: null
layout_spectrum: 0.88234299630858
typography_spectrum: 0.04723858251236379
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.20585602801293135
  lightness: 0.3469419153407216
  saturation: 0.6753275510855019
  rhythmicContrast: 0.28279419406317174
purpose: []
